apiVersion: v2
name: jenkins-wrapper
description: HomeLab Jenkins wrapper chart
type: application
version: 0.1.0

dependencies:
  - name: jenkins
    version: "5.9.18"
    repository: "https://charts.jenkins.io"
