controller:

  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts-jdk17

  imagePullPolicy: IfNotPresent

  admin:
    createSecret: true
    username: admin
    password: admin123

  serviceType: NodePort
  nodePort: 32000

  agentListenerServiceType: ClusterIP

  legacyRemotingSecurityEnabled: false

  installPlugins:

    # Kubernetes
    - kubernetes
    - kubernetes-cli
    - kubernetes-credentials
    - kubernetes-credentials-provider

    # GitHub
    - git
    - git-client
    - github
    - github-branch-source

    # Pipelines
    - workflow-aggregator
    - workflow-job
    - workflow-multibranch
    - pipeline-model-definition
    - pipeline-stage-view
    - pipeline-utility-steps
    - docker-workflow

    # Security / Credentials
    - credentials
    - credentials-binding
    - plain-credentials
    - ssh-credentials

    # Automation
    - configuration-as-code
    - job-dsl
    - ansible

    # Vault
    - hashicorp-vault-plugin
    - hashicorp-vault-pipeline

    # UI
    - dark-theme
    - theme-manager

  installLatestPlugins: false
  installLatestSpecifiedPlugins: false

  initializeOnce: true
  overwritePlugins: true
  overwritePluginsFromImage: true

  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"

    limits:
      cpu: "2000m"
      memory: "4Gi"

  ingress:
    enabled: false

  JCasC:
    defaultConfig: false
    overwriteConfiguration: true

    configScripts:

      system-message: |
        jenkins:
          systemMessage: "HomeLab Jenkins managed by Helm + JCasC + Vault"

      security: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: admin
                  password: admin123

          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

      location: |
        unclassified:
          location:
            url: "http://192.168.1.91:32000/"

      vault-config: |
        unclassified:
          hashicorpVault:
            configuration:
              vaultUrl: "http://vault.vault.svc.cluster.local:8200"
              engineVersion: 2
              skipSslVerification: true

agent:
  enabled: true

  websocket: false
  directConnection: false

  podRetention: Never

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"

    limits:
      cpu: "1000m"
      memory: "1Gi"

persistence:
  enabled: true

  storageClass: longhorn

  accessMode: ReadWriteOnce

  size: 20Gi

rbac:
  create: true
  readSecrets: true

serviceAccount:
  create: true
  name: jenkins

serviceAccountAgent:
  create: false

networkPolicy:
  enabled: false
