# Homepage Development Environment
environment: dev
namespace: homepage-dev

replicaCount: 1

image:
  repository: 192.168.1.91:32500/homepage
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 3000
  nodePort: 32301

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  storageClass: longhorn
  size: 500Mi
  accessMode: ReadWriteOnce

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "192.168.1.91:32301"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

# ConfigMap configs
config:
  services:
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: DEV Environment
  
  settings:
    title: Homepage Dev
    tagline: Development Environment
    theme: dark
    color: slate
    language: en
    timezone: America/Mexico_City
    background:
      opacity: 50

  widgets:
    - resources:
        index: 0
        cpu: true
        memory: true
        disk: /
    - search:
        index: 1
        provider: google
        target: _blank
    - datetime:
        index: 2
        format:
          timeStyle: short
          dateStyle: medium
        timezone: America/Mexico_City
