---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Personal Homepage
tagline: My custom homepage
theme: dark
color: "slate" # Tailwind CSS color or hex code
language: en
timezone: America/Mexico_City

background:
   #image: https://images.unsplash.com/photo-1628660541287-982dc7774ca1?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2670
   opacity: 50 #0-100
  # position: center
  # size: cover
  # repeat: no-repeat
  # overlay: rgba(0, 0, 0, 0.5) # optional overlay color

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
