apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibreweb-data
  labels:
    {{- include "calibreweb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: calibreweb-data-pv
  storageClassName: ""
